allowCompoundWords: true
dictionaries:
  - bash
  - companies
  - cpp
  - cpp-legacy
  - docker
  - en_shared
  - en-freq
  - en-gb
  - en_us
  - fonts
  - git
  - markdown
  - misc
  - npm
  - shell
  - softwareTerms
  - vim
enableGlobDot: true
features:
  weighted-suggestions: true
globRoot: ${cwd}
ignorePaths:
  - .*ignore
  - .git
  - .github/CODE_OF_CONDUCT.*
  - .vscode/extensions.json
  - cspell.config.yml
language: en,ja
useGitignore: true
version: "0.2"
words:
  - aegisub
  - alcom
  - alsa
  - antlr
  - apic
  - biosapic
  - bioslogofadein
  - broot
  - cfprefsd
  - clmv
  - cura
  - glab
  - gotop
  - dsound
  - hpet
  - hwvirtex
  - imgbotconfig
  - ioapic
  - ionescu
  - iZotope
  - karabiner
  - kito
  - kotoeri
  - kurone
  - kuroné
  - lporg
  - mackup
  - maxon
  - modifyvm
  - mswin
  - nyancat
  - osascript
  - pfind
  - pkill
  - scrcpy
  - sorin
  - spctl
  - steamcmd
  - usbxhci
  - ultimaker
  - usbxhci
  - vbguest
  - vtxux
  - vtxvpid
  - wkhtmltopdf
  - zprezto
