#!/bin/sh
# vim: set ft=sh :

set -eu
cd $(dirname $0)

sudo -v
while true; do sleep 50; sudo -n true; kill -0 "$$" || exit; done 2>/dev/null &

./.setup.xcode-select.sh
./.setup.brew.sh
./.setup.xcode-build.sh
./.setup.git.sh
./.setup.virtualization.sh
./.setup.prezto.sh
./.setup.anyenv.sh
./.setup.defaults.sh
./.setup.network.sh
