#!/bin/sh
# -*- mode: sh -*-
# vim: set ft=sh :

set -eu
cd "$(cd "$(dirname "$0")"; pwd)"
. libs/lib.sh

sudo -v
while true; do sleep 50; sudo -n true; kill -0 "$$" || exit; done 2>/dev/null &

libs/update.sh

libs/xcode-select.sh
libs/brew-install.sh
libs/brew-pre-bundle.sh
libs/xcode-build.sh

BREW="$(pwd)/libs/brew-bundle.sh"
osascript -e 'tell app "Terminal"' -e "do script \"${BREW} && exit\"" -e 'end tell'

libs/updaters.sh
libs/nanorc.sh
libs/git.sh
libs/prezto.sh
libs/zsh.d.sh
libs/dotfiles.sh
libs/asdf.sh
libs/mkcert.sh
libs/vagrant.sh
libs/docker.sh
libs/unity.sh

log_complete
