#!/bin/sh
# -*- mode: sh -*-
# vim: set ft=sh :

# The following lines have been added by Docker Desktop to enable Docker CLI completions.
if [ -d "$HOME/.docker/completions" ]; then
  fpath=($HOME/.docker/completions $fpath)
  autoload -Uz compinit
  compinit
fi
# End of Docker CLI completions
