#!/bin/sh
# -*- mode: sh -*-
# vim: set ft=sh :

BREWPATH=''
if [ -f /usr/local/bin/brew ]
then
  BREWPATH='/usr/local/bin/brew' # x86_64
fi
if [ -f /opt/homebrew/bin/brew ]
then
  BREWPATH='/opt/homebrew/bin/brew' # arm64
fi
if [ -f "${HOME}/homebrew/bin/brew" ]
then
  BREWPATH="${HOME}/homebrew/bin/brew" # userdir
fi

if [ -x "${BREWPATH}" ]
then
  eval "$("${BREWPATH}" shellenv)"
  REPO="$(brew --repository)"
  HB_CNF_HANDLER="${REPO}/Library/Taps/homebrew/homebrew-command-not-found/handler.sh"
  if [ -f "${HB_CNF_HANDLER}" ]; then
    # shellcheck disable=SC1090
    . "${HB_CNF_HANDLER}";
  fi
fi
