#!/bin/sh
# -*- mode: sh -*-
# vim: set ft=sh :

# =========================================================
# ! WARN: DO NOT REMOVE THE “z” PREFIX!
#
# Added the “z” prefix to the filename because
# the script has to run it after Homebrew's path resolution.

ASDF_DIR="$(brew --prefix asdf)/libexec"
ASDF_SH="${ASDF_DIR}/asdf.sh"
export ASDF_DIR
# shellcheck disable=SC1090
[ -f "${ASDF_SH}" ] && . "${ASDF_SH}"
